name: Simple Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST:
      EC2_USER: ec2-user
      EC2_SSH_KEY: |
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/apps/cartech-ui
            git pull origin main
            npm install --omit=dev
            pm2 restart cartech-ui || pm2 start npm --name "cartech-ui" -- start
            pm2 save
